In [1]:
!pip install -U fortran-magic
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00',
                             '2017-01-07 00:00:00+00:00',
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [2]:
assert ran_the_first_cell, "Oh noes!"

In [3]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [4]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [5]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [6]:
# Lists can also be sliced, which makes a copy of elements between
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [7]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [8]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [9]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [10]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [11]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [12]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [13]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}

In [14]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'David': 'Hume',
 'Immanuel': 'Kant',
 'Bertrand': 'Russell',
 'Ludwig': 'Wittgenstein'}

In [15]:
del philosophers['David']
philosophers

{'Immanuel': 'Kant', 'Bertrand': 'Russell', 'Ludwig': 'Wittgenstein'}

In [16]:
# No slicing.
#philosophers['Bertrand':'Immanuel']
#Este comando no puede ser aplicado sobre el diccionario

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [17]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [18]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [19]:
%%time

matmul(a, b)

CPU times: user 39 µs, sys: 6 µs, total: 45 µs
Wall time: 49.6 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

**My own example 0 - cpu info**

In [20]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
addres

**My own example 1 - Changing in matmul(A, B) Python len(B) (# of rows of B) for len(A[0]) (# of columns of A)**

In [21]:
def matmul(A, B):
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(A[0])):
                out[i][j] += A[i][k] * B[k][j]
    return out

**My own example 2 - Verifiying error with in matmul(A, B) Python with the original matrices when changing len(B) (# of rows of B) for len(A[0]) (# of colums of A)**

In [22]:
#matmul(a, b)
#Las dimensiones de las matrices no son compatibles, la operacion no esta definida y por lo tanto no se puede realizar

**My own example 3 - Chekcing the mtarix multiplication compatibility condition  len(A[0]) == len(B)**

In [23]:
def matmul(A, B):
    if len(A[0]) == len(B):
      rows_out = len(A)
      cols_out = len(B[0])
      out = [[0 for col in range(cols_out)] for row in range(rows_out)]

      for i in range(rows_out):
          for j in range(cols_out):
              for k in range(len(A[0])):
                  out[i][j] += A[i][k] * B[k][j]
    else:
      print("No son compatibles las dimensiones de las matrices.")
      return
    return out

**My own example 4 -  Verifiying error with in matmul(A, B) Python when checking the mtarix multiplication compatibility condition  len(A[0]) == len(B)**

In [24]:
%%time

matmul(a, b)

No son compatibles las dimensiones de las matrices.
CPU times: user 1.03 ms, sys: 5 µs, total: 1.04 ms
Wall time: 1.05 ms


**My own example 5 - Deifining A and B that are compatible for multiplcation**

In [25]:
A = [[1, 10, 5],
     [3, 5, 13]]

B = [[56, 17, 32, 14],
     [2, 21, 9, 11],
     [1, 3, 6, 13]]

**My own example 6 - Runinng the correct Python matrix multiplication code with the matrices with dimensions compatible for multiplication.**

In [26]:
%%time

matmul(A, B)

CPU times: user 27 µs, sys: 4 µs, total: 31 µs
Wall time: 35 µs


[[81, 242, 152, 189], [191, 195, 219, 266]]

In [27]:
import random

In [28]:
random.normalvariate(0,1)

-0.9563485088836475

In [29]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.15464517107761722, 0.7846351511818179, 0.39759633124432436],
 [0.44058144767660845, 0.6315332655562981, 0.7701843714019925]]

**My own example 7 - Running 10 times matmul(randa, randb) with randa and randb a randon matrices of 600 x 100 and 100 x 600 and calulating the average execution time**

In [30]:
random_A = random_matrix(600,100)
random_B = random_matrix(100,600)
for i in range(10):
  matmul(random_A, random_B)

In [31]:
import time

average = 0
for i in range(10):
  start = time.process_time()
  matmul(random_A, random_B)
  end = time.process_time()
  Ttime = end-start
  print("Iteration No.", i+1,"--  Time: ", Ttime)
  average += Ttime

average = average/10
print("Average: ",average)

Iteration No. 1 --  Time:  13.57953395700001
Iteration No. 2 --  Time:  8.731850031999997
Iteration No. 3 --  Time:  9.349002447999993
Iteration No. 4 --  Time:  9.231614074999982
Iteration No. 5 --  Time:  10.43417678999998
Iteration No. 6 --  Time:  7.802966884999989
Iteration No. 7 --  Time:  9.207406046999978
Iteration No. 8 --  Time:  8.829438229999994
Iteration No. 9 --  Time:  7.853160154000022
Iteration No. 10 --  Time:  9.070929861999986
Average:  9.409007847999993


**My own example 8 - Creating the average execution time data frame and adding Python's average execution time**

In [32]:
import pandas as pd

def new_Data(df, lenguaje, tiempo):
  new_df = pd.DataFrame({'Lenguaje':[lenguaje],'Promedio (s)':[tiempo]})
  return df.append(new_df, ignore_index=True)

dFrame=pd.DataFrame({'Lenguaje':[],'Promedio (s)':[]})
dFrame= new_Data(dFrame,"Python",average)
dFrame

<ipython-input-32-a859e4b11f72>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  return df.append(new_df, ignore_index=True)


Lenguaje  Promedio (s)
0   Python      9.409008

**My own example 9 - Running 10 times randa and randb mutiplicaction as NumPy arrays  adding NumPy's average execution time**

In [33]:
import numpy as np
import time

X = np.array(random_A)
Y = np.array(random_B)

average = 0
for i in range(10):
  start = time.process_time()
  Z = X@Y
  end = time.process_time()
  TotalT = end-start
  average += TotalT

average = average/10
dFrame.loc[len(dFrame.index)] = ['Numpy', average]
display(dFrame)

Lenguaje  Promedio (s)
0   Python      9.409008
1    Numpy      0.006340

In [34]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 9.12 s, sys: 111 ms, total: 9.23 s
Wall time: 9.24 s


In [35]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [36]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result

    result = sum(xs * ys)
end

In [37]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [38]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 13 ms


333328333350000.0

In [39]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 210 µs, sys: 0 ns, total: 210 µs
Wall time: 217 µs


333328333350000.0

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


**My own example 10 - Deifining A (2x2)  and B (2x2)**

In [40]:
A = [[100, 25],
     [56, 420]]

B = [[18, 99],
     [123, 12]]

**My own example 11 - Defining Fortran subroutine matmul(A,B) for 2x2 matrices**

In [41]:
%%fortran
subroutine fortran_matmul(A,B,S)
     double precision, dimension(:,:), intent(in) :: A
     double precision, dimension(:,:), intent(in) :: B
     double precision, dimension(2,2), intent(out) :: S

  S = matmul(A,B)

end

**My own example 12 -Run Fortran subroutine matmul(A,B) with a and b 2x2 matrices**

In [42]:
%%time
fortran_matmul(A,B)

CPU times: user 35 µs, sys: 0 ns, total: 35 µs
Wall time: 39.1 µs


array([[ 4875., 10200.],
       [52668., 10584.]])

**My own example 13 - Defining Fortran subroutine matmul(A,B) for 600x100 and 100x600 matrices**

In [43]:
%%fortran
subroutine fortran_matmul(X,Y,Z)
     double precision, dimension(:,:), intent(in) :: X
     double precision, dimension(:,:), intent(in) :: Y
     double precision, dimension(600,600), intent(out) :: Z

  Z = matmul(X,Y)

end

**My own example 14 -Run Fortran subroutine matmul(A,B) with 600x100 and 100x600 matrices**

In [44]:
%%time
fortran_matmul(random_A,random_B)

CPU times: user 13.1 ms, sys: 999 µs, total: 14.1 ms
Wall time: 14.1 ms


array([[27.53137553, 26.14376945, 25.0251181 , ..., 27.34800564,
        29.67727395, 29.19950423],
       [26.39651578, 23.76332754, 22.9993793 , ..., 25.40183413,
        26.22731497, 28.82014893],
       [25.55416945, 25.75336374, 23.47745722, ..., 25.65461561,
        26.71554664, 28.63900724],
       ...,
       [27.53750358, 24.41024076, 23.63497819, ..., 26.03048125,
        29.14710966, 28.87547819],
       [28.80165666, 27.49777242, 25.48592972, ..., 26.5808311 ,
        27.40832958, 30.35210405],
       [24.62342204, 23.59562277, 22.85041364, ..., 25.33840414,
        26.88229576, 26.91500552]])

**My own example 15 - Running 10 times the  Fortran subroutine matmul(A,B) with 600x100 and 100x600 matrices and adding Fortran magic average execution time to the data frame**

In [45]:
import time
average = 0
for i in range(10):
  start = time.process_time()
  fortran_matmul(random_A,random_B)
  end=time.process_time()
  TotalT = end-start
  average += TotalT

average = average/10

dFrame.loc[len(dFrame.index)] = ['Fortranmagic', average]
display(dFrame)

Lenguaje  Promedio (s)
0        Python      9.409008
1         Numpy      0.006340
2  Fortranmagic      0.011675

**My own example 16 - Creating a  Fortran program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [46]:
%%writefile matprod.f
        program matprod

            integer :: a = 600
            integer :: b = 100
            integer :: c = 600

            real :: H,sta,fin

            integer :: l, m, n, o

            double precision, dimension(600,100) :: X
            double precision, dimension(100,600) :: Y
            double precision, dimension(600,600) :: Z

            do m = 1, a
                do n = 1, a
                   X(m, n)= m+n * 0.1
                end do
            end do

           do m = 1, b
                 do n = 1, c
                    Y(m, n)= m+n * 0.5
                 end do
           end do

           H = 0.0

           do l = 1, 10
               call cpu_time(sta)
               Z = matmul(X,Y)
              call cpu_time(fin)
               H = H + (fin-sta)
           end do
           H = H/10.0
        PRINT *, H
      stop
      end

Overwriting matprod.f


**My own example 17 - Running the Fortran program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [47]:
!gfortran matprod.f -o matprod
!./matprod

   5.70530072E-03


**My own example 18 - Adding Fortran average execution time to the data frame**

In [48]:
dFrame.loc[len(dFrame.index)] = ['Fortran', 8.81369971E-03]
display(dFrame)

Lenguaje  Promedio (s)
0        Python      9.409008
1         Numpy      0.006340
2  Fortranmagic      0.011675
3       Fortran      0.008814

**My own example 19 - Creating a c program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [49]:
%%writefile matmul_c.c

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main() {
    int value = 10;
    FILE *file;

    int A[600][100];
    for (int i = 0; i < 600; i++) {
        for (int j = 0; j < 100; j++) {
            A[i][j] = value + i + j;
        }
    }

    int B[100][600];
    for (int i = 0; i < 100; i++) {
        for (int j = 0; j < 600; j++) {
            B[i][j] = value + i + j;
        }
    }

    int result[600][600];

    clock_t start, end;
    double total_time = 0.0;

    for (int repetition = 0; repetition < 10; repetition++) {
        start = clock();

        for (int i = 0; i < 600; i++) {
            for (int j = 0; j < 600; j++) {
                result[i][j] = 0;
                for (int k = 0; k < 100; k++) {
                    result[i][j] += A[i][k] * B[k][j];
                }
            }
        }

        end = clock();
        total_time += (double)(end - start) / CLOCKS_PER_SEC;
    }

    total_time = total_time / 10;
    printf("%f\n", total_time);

    file = fopen("c_total.txt", "w+");
    fprintf(file, "%f", total_time);
    fclose(file);

    return 0;
}

Overwriting matmul_c.c


**My own example 20 - Running the c program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [50]:
!gcc matmul_c.c -o matmul_c
!./matmul_c

0.164231


**My own example 21 - Adding c average execution time to the data frame**

In [51]:
avg_file = 0.0
with open("c_total.txt", "r") as file:
    avg_file = float(file.readline())
dFrame.loc[len(dFrame.index)] = ['C', avg_file]
display(dFrame)

Lenguaje  Promedio (s)
0        Python      9.409008
1         Numpy      0.006340
2  Fortranmagic      0.011675
3       Fortran      0.008814
4             C      0.164231

**My own example 22 - Creating a C++ program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [52]:
%%writefile matmul_c++.cc
#include <iostream>
#include <ctime>

using namespace std;

int main() {
    int value = 10;
    FILE *file;

    int A[600][100];
    for (int i = 0; i < 600; i++) {
        for (int j = 0; j < 100; j++) {
            A[i][j] = value + i + j;
        }
    }

    int B[100][600];
    for (int i = 0; i < 100; i++) {
        for (int j = 0; j < 600; j++) {
            B[i][j] = value + i + j;
        }
    }

    int result[600][600];

    unsigned start, end;
    double total_time = 0.0;

    for (int repetition = 0; repetition < 10; repetition++) {
        start = clock();

        for (int i = 0; i < 600; i++) {
            for (int j = 0; j < 600; j++) {
                result[i][j] = 0;
                for (int k = 0; k < 100; k++) {
                    result[i][j] += A[i][k] * B[k][j];
                }
            }
        }

        end = clock();
        total_time += double(end - start) / CLOCKS_PER_SEC;
    }

    total_time = total_time / 10;
    cout << total_time << endl;

    file = fopen("c++_total.txt", "w+");
    fprintf(file, "%f", total_time);
    fclose(file);

    return 0;
}

Overwriting matmul_c++.cc


**My own example 23 - Running the C++ program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [53]:
!g++ matmul_c++.cc -o matmul_c++
!./matmul_c++

0.268563


**My own example 24 - Adding C++ average execution time to the data frame**

In [54]:
ans = open("c++_total.txt",'r')
avg_file = float(ans.readline())
dFrame.loc[len(dFrame.index)] = ['C++', avg_file]
display(dFrame)

Lenguaje  Promedio (s)
0        Python      9.409008
1         Numpy      0.006340
2  Fortranmagic      0.011675
3       Fortran      0.008814
4             C      0.164231
5           C++      0.268563

**My own example 25 - Creating a Java program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [55]:
%%writefile matmulJava.java
import java.io.FileWriter;
import java.io.IOException;

class matmulJava {

    public static void main(String[] args) {

        int value = 10;

        int[][] A = new int[600][100];
        for (int i = 0; i < 600; i++) {
            for (int j = 0; j < 100; j++) {
                A[i][j] = value + i + j;
            }
        }

        int[][] B = new int[100][600];
        for (int i = 0; i < 100; i++) {
            for (int j = 0; j < 600; j++) {
                B[i][j] = value + i + j;
            }
        }

        int[][] result = new int[600][600];

        long start, stop;
        double total = 0.0;

        for (int repetition = 0; repetition < 10; repetition++) {
            start = System.currentTimeMillis();

            for (int i = 0; i < 600; i++) {
                for (int j = 0; j < 600; j++) {
                    result[i][j] = 0;
                    for (int k = 0; k < 100; k++) {
                        result[i][j] += A[i][k] * B[k][j];
                    }
                }
            }

            stop = System.currentTimeMillis();
            total += (stop - start) / 1000.0;
        }
        total = total / 10;
        System.out.println(total);

        try {
            FileWriter archivo = new FileWriter("java_total.txt");
            archivo.write(Double.toString(total));
            archivo.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

Overwriting matmulJava.java


**My own example 26 - Running the Java program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [56]:
!javac matmulJava.java
!java matmulJava

0.05349999999999999


**My own example 27 - Adding Java average execution time to the data frame**

In [57]:
ans = open("java_total.txt",'r')
avg_file = float(ans.readline())
dFrame.loc[len(dFrame.index)] = ['Java', avg_file]
display(dFrame)

Lenguaje  Promedio (s)
0        Python      9.409008
1         Numpy      0.006340
2  Fortranmagic      0.011675
3       Fortran      0.008814
4             C      0.164231
5           C++      0.268563
6          Java      0.053500

**My own example 28 - Creating a Javascript program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [58]:
%%writefile matmulJS.js

const { performance } = require('perf_hooks');
const fs = require("fs");

//------------------------------
var value = 10;

let A = [];
for (let i = 0; i < 600; i++) {
    A[i] = [];
    for (let j = 0; j < 100; j++) {
        A[i][j] = value + i + j;
    }
}

//------------------------------

let B = [];
for (let i = 0; i < 100; i++) {
    B[i] = [];
    for (let j = 0; j < 600; j++) {
        B[i][j] = value + i + j;
    }
}

//------------------------------
let result = [];

// Realizar la multiplicación 10 veces

var total = 0.0;
let startTime = 0;
let stopTime = 0;

for (let repetition = 0; repetition < 10; repetition++) {
    startTime = performance.now();

    // Realizar la multiplicación de matrices
    for (let i = 0; i < 600; i++) {
        result[i] = [];
        for (let j = 0; j < 600; j++) {
            result[i][j] = 0;
            for (let k = 0; k < 100; k++) {
                result[i][j] += A[i][k] * B[k][j];
            }
        }
    }

    stopTime = performance.now();
    total += stopTime - startTime;
}

total = total / 1000;
console.log(total);

Overwriting matmulJS.js


**My own example 29 - Running the Javascript program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [59]:
!node matmulJS.js

2.3357928519998676


**My own example 30 - Adding Javascript average execution time to the data frame**

In [60]:
dFrame.loc[len(dFrame.index)] = ['JavaScript', 3.674580220999196]
display(dFrame)

Lenguaje  Promedio (s)
0        Python      9.409008
1         Numpy      0.006340
2  Fortranmagic      0.011675
3       Fortran      0.008814
4             C      0.164231
5           C++      0.268563
6          Java      0.053500
7    JavaScript      3.674580

**My own example 31 - Finding the minimun average esecuiton time in the data frame**

In [61]:
min_avg=min(dFrame["Promedio (s)"])
min_avg

0.006340383900001712

**My own example 32 - Adding the Speed factor columne to the data frame**

In [62]:
dFrame["Speed Factor"]=dFrame["Promedio (s)"]/min_avg

**My own example 33 - Sorting the the data frame by average execution time**

In [63]:
dFrame.sort_values(by=['Promedio (s)'])
dFrame

Lenguaje  Promedio (s)  Speed Factor
0        Python      9.409008   1483.980780
1         Numpy      0.006340      1.000000
2  Fortranmagic      0.011675      1.841340
3       Fortran      0.008814      1.390089
4             C      0.164231     25.902375
5           C++      0.268563     42.357530
6          Java      0.053500      8.437975
7    JavaScript      3.674580    579.551693

## Why is the Python Version so Much Slower?

In [64]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [65]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [66]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [67]:
data + data

array([2, 4, 6, 8])

In [68]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 1.36 ms, sys: 0 ns, total: 1.36 ms
Wall time: 1.43 ms


333328333350000.0

In [69]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 2.04 ms, sys: 6 µs, total: 2.05 ms
Wall time: 1.33 ms


333328333350000.0

In [70]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 225 µs, sys: 2 µs, total: 227 µs
Wall time: 198 µs


333328333350000.0

In [71]:
# Numpy won't allow us to write a string into an int array.
# data[0] = "foo"

In [72]:
# We also can't grow an array once it's created.
# data.append(3)

In [73]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [74]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [75]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [77]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [78]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [79]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [80]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [81]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [82]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [83]:
sines[:3]  # First three elements

array([0.        , 0.34185385, 0.64251645])

In [84]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [85]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [86]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [87]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [88]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [89]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [90]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [91]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [92]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [93]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [94]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [95]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [96]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [97]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [98]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [99]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [100]:
variance(np.random.standard_normal(1000))

0.9901774824001438

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [101]:
data = np.arange(30)
data.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [102]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [103]:
data.mean()

14.5

In [104]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [105]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [106]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [107]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [108]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for:
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [109]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [110]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [111]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [112]:
# ... or by label.
s.loc['a']

1

In [113]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [114]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [115]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [116]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [117]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [118]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [119]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [122]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)

    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!